# в этом файле описывается конкретно под
apiVersion: v1 # ХЗ что это)
kind: Pod # Сущность которую мы хотим пульнуть в кубер
metadata: # Вся общая инфа по этой сущности
  name: app-koa-server-pod-via-yaml # название сущности
  labels: # метки которые будут приаттачены к этому поду
    environment: pre-prod # метка в стиле ключ: значение
spec: # что в этой сущности будет находится
  nodeSelector: # выбираем к какому узлу ( node ) будет приаттачен этот под
    gpu: "true" # метка в ноде ( ключ: "значение" )
  containers: # перечисляем контейнеры
  - name: container-for-pod-from-06-lesson # название контейнера который будет крутиться в поде
    image: luckytwixy/koa-serve-image # образ, из котрого будет создаваться контейнер
    ports: # порты контейнера, если честно не много не понял какие еще там могут быть.
    - containerPort: 3000 # порт на котором сидит наше приложение.