apiVersion: v1
kind: Service
metadata:
  name: kuber--deployment-lesson--service
spec:
  selector:
    first-label-for-pod-watcher: label-name-of-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
