apiVersion: apps/v1 # версия кубера по которой он будет грузить конфиг
kind: ReplicaSet # Сущность которую мы хотим пульнуть в кубер
metadata: # Вся общая инфа по этой сущности
  name: 02-replica-set--match-labels # название сущности
spec: # что в этой сущности будет находится
  replicas: 3 # количество шаблонов (template) которое должно быть в ReplicaSet
  selector: # Настройки по каким данным ReplicaSet будет определять поды
    matchExpressions: # Более детальная настройка слежки за подами. Указанные тут значение должны совпасть все, для создания этого файла
      - key: label-for-first-matcher # название метки котрую нужно указать в template
        operator: In # In, NotIn - означают что поды должны иметь/не иметь в метке label-for-first-matcher перечисленные значения в ключе values, как свои значения меток
        values: # передавая таким образом мы говорим что бы ReplicaSet следил или за kuber или за koa-server в label-for-first-matcher
          - kuber
          - koa-server
      - key: label-for-second-matcher # название метки котрую нужно указать в template
        operator: Exists # Exists, DoesNotExist - означают что под должен иметь/не иметь такую метку, не важно с каким она будет значением
  template:  # Шаблон пода за котороым будет следить ReplicaSet
    metadata: # Вся общая инфа по этой сущности из шаблона
      name: kuber-pod-for--02-replica-set--match-labels # название пода
      labels: # метки которые будут приаттачены к этому поду
        app: 02-replica-set--match-labels # метка в стиле ключ: значение
        label-for-first-matcher: koa-server # метка в стиле ключ: значение
        label-for-second-matcher: abra-kadbra
    spec: # что в этой сущности будет находится
      containers: # перечисляем контейнеры
      - name: koa-server--pod-container-for--02-replica-set--match-labels # название контейнера который будет крутиться в поде
        image:  luckytwixy/koa-serve-image:0.1 # образ, из которого будет создаваться контейнер
        ports: # порты контейнера
        - containerPort: 3000 # порт на котором сидит наше приложение.